source 'https://rubygems.org'

gem 'fluentd', '~> 1.14.2'
gem 'fluent-plugin-multi-format-parser'
gem 'oj'
gem 'fluent-plugin-insert-id'
gem 'fluent-plugin-gcs'
gem 'fluent-plugin-kafka'
gem 'fluent-plugin-elasticsearch'
gem 'fluent-plugin-forest'
gem 'fluent-plugin-gcloud-pubsub-custom'
